# Generated by Django 4.1.4 on 2022-12-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('InvoiceDate', models.DateTimeField()),
                ('CustomerID', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('StockCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('InvoiceNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database1C.invoice')),
                ('StockCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database1C.stock')),
            ],
        ),
    ]
